services:
  postgres:
    container_name: postgres_go
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgres
    ports:
      - "5432:5432"
  wallet-app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8081:8081"